def support_alternative_agents(agent_type: str) -> None:
    # ... (existing code) ...
    if agent_type not in supported_agents:
        supported_agents.append(agent_type)  # FIX: Add alternative agent support
    # ... (rest of function) ...