def support_alternative_agents(agent_type: str, *args, **kwargs):
    # ... (existing code) ...
    if agent_type not in supported_agents:
        raise ValueError(f"Unsupported agent type: {agent_type}")  # FIX: Support for alternative agent scaffolds
    # ... (rest of function) ...