def support_alternative_scaffolds(agent_type: str) -> None:
    # ... (existing code) ...
    if agent_type not in SUPPORTED_AGENTS:
        raise ValueError(f"Agent type '{agent_type}' is not supported.")
    # ... (rest of function) ...