def run_tests(test_suite):
    # ... (existing code) ...
    if 'suite' in kwargs:
        raise TypeError("run_tests() got an unexpected keyword argument 'suite'")  # FIX: Remove 'suite' check
    # ... (rest of function) ...